### ISSUE TITLE
Can a bug be optimized?

### ISSUE THREAD

**Issue by dnknn** [moneytoo/DontCloseWindowWithLastTab#5]
Hi:) ✿(。◕‿◕。)✿
https://chrome.google.com/webstore/detail/dlnpfhfhmkiebpnlllpehlmklgdggbhn
`Don't Close Window With Last Tab`  abbr to `DCWWLT`

`DCWWLT` is a excellent extension and smarter than others, because it can be achieved👇
          
          💪Prevent closing of first opened window (Other windows are not affected)💪

But I found that there is a deficiency, `DCWWLT` can only operate on a single tab, 
## but it cannot work for the closing of multi-selected tabs.

> Just like windows file-explorer, 
Chrome natively support:  holding ⌨<kbd>Ctrl or Shift</kbd> on the tab bar to multiple-selected tags, and then multiple operations. 

GIF recording demo👇 Close<kbd>Ctrl+W</kbd> of **single** tab, is no problem, 
### However, if **multiple** **tabs** of **multiple** **selected** are closed<kbd>Ctrl+W</kbd> **together**, the browser will be **exited**.

![bug](https://user-images.githubusercontent.com/10995302/86507905-38346980-be0e-11ea-8b8a-497ef0c70969.gif)

**Comment by moneytoo** [comment]
To fix this use case, this extension would have to keep its pinned tab always visible. It would have to be configurable... However I think that there are already extensions like this available (that keep one pinned tab always open). Also including the one pinned tab in a selection would also close the window.
I'm afraid that this is outside my scope as I think that this use case is quite rare and I if anything, I should improve the use with user pinned tabs in the first place.

**Comment by dnknn** [comment]
Um, i don't know the logic principle inside the browser,
and it doesn't matter. It's not critical, I just mentioned that there is such a situation for you to know.
It would be perfect if it could be improved, and If it’s not easy to do it, it’s not a big problem also.
